name: codelab_engine
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.9.0
  codelab_uikit: any
  codelab_core: any

  cupertino_icons: ^1.0.8
  code_text_field: ^1.1.0
  highlight: ^0.7.0
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  freezed_annotation: ^3.1.0
  file_picker: ^10.3.3
  process_run: ^1.2.4
  path: ^1.9.1
  file: ^7.0.1
  xterm: ^4.0.0
  logger: ^2.6.2
  flutter_highlight: ^0.7.0
  flutter_code_editor: ^0.3.5
  cherrypick: ^3.0.2
  cherrypick_annotations: ^3.0.1
  cherrypick_flutter: ^3.0.2
  fluent_ui: ^4.13.0
  fpdart: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^3.1.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  cherrypick_generator: ^3.0.1
