name: codelab_uikit
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.13.0
  flutter_code_editor: ^0.3.5
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  # path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  lints: ^6.0.0
  test: ^1.25.6
