name: codelab_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: '>=3.10.1 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.9.0
  file_picker: ^10.3.3
  path: ^1.9.1
  file: ^7.0.1
  logger: ^2.6.2
  fpdart: ^1.2.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.6
