name: codelab_ai_assistant
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.9.0
  codelab_uikit: any
  fluent_ui: ^4.13.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
