name: codelab_ai_assistant
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: '>=3.10.1 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.9.0
  codelab_uikit: any
  fluent_ui: ^4.13.0
  web_socket_channel: ^3.0.3
  cherrypick: ^3.0.2
  cherrypick_annotations: ^3.0.1
  cherrypick_flutter: ^3.0.2
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  json_annotation: ^4.9.0
  gpt_markdown: ^1.1.4
  path: ^1.9.1
  codelab_core: any
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.5.4
  cherrypick_generator: ^3.0.1
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lints: ^6.0.0
  test: ^1.25.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
